server:
  port: 8080
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/database
      username: username
      password: password
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  redis:
    host: 139.196.48.244
    port: 6379
    password: 123456
    database: 0
    jedis:
      pool:
        enabled: true
        max-active: 8
        max-wait: 1ms
        max-idle: 4
        min-idle: 0


mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
  mapper-locations: "classpath:/mapper/**/*.xml"

reggie:
  path: "D:\\"
  access-key-id: "access-key-id"
  access-key-secret: "access-key-secret"